# 选择模型
model_name: 'RG_GRU_AdamW_atomOrder'

# 编辑实验名称
experiment_name: '1024_0d0025_500_1b1'

folds: [0]

device: 'cuda:1'

# bsz=1024->best_num_workers=8 for linx
train:
  batch_size: 1024
  lr: 0.0025
  epochs: 500
  loss_fn: 'CrossEntropyLoss'
  optimizer:
    name: 'AdamW'
    # 默认1e-2
    weight_decay: 0.01
  dropout: 0.1
  num_workers: 8
  multiproc_max_workers: 3
  seed: 42

model:
  block:
    num: 3
    ffn:
      hidden_dim: 2048
  mlp:
    hidden_dim: 256
  attn_heads: 5
  is_rg: true
  is_norm_adj: false

data:
  # note: 修改了数据集一定要记得修改分类数
  source: "Deng"
  num_classes: 65
  atom_dim: 75
  clip_num_atom: 50
